apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  # defines which pods is this deployment managing
  selector:
    matchLabels:
      app: posts
  # defines how the pods should look like
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: mp3por/posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  type: ClusterIP
  # tells the service which pods to expose
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # external port
      targetPort: 4000 # internal port
